title: "Jekyll-Theme-MDUI"
description: "A Jekyll theme based on MDUI"
url: "https://github.com/thenerdtavern/"
baseurl: "project-v2"
author: "KeJun"
paginate: 5
paginate_path: "/blog/page:num/"


# Build settings
theme: jekyll-theme-mdui
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
